#!/bin/sh
rm -rf src-cordova/res/screen
rm -rf src-cordova/platforms/android/app/src/main/res/drawable*

quasar build -m cordova -T android
cp src-cordova/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk app.apk

jarsigner -sigalg SHA1withRSA \
  -digestalg SHA1 \
  -keystore GNovaes.keystore \
  -storepass $(<~/.keystorepass) \
  app.apk GNovaesApps

adb install -r app.apk
adb shell pm clear br.com.gustavonovaes.smrcoletor
adb shell am start -n br.com.gustavonovaes.smrcoletor/br.com.gustavonovaes.smrcoletor.MainActivity
