#!/bin/bash

_VERSION="$1"

[[ -z "$_VERSION" ]] && { echo "Versão não especificada. Tente: $0 <versao>"; exit 1; }

git flow release start $_VERSION
sed -i "s/\"version\":.*/\"version\": \"$_VERSION\",/" ./package.json
sed -i "s/<em>v[0-9.]*<\/em>/<em>v$_VERSION<\/em>/" ./src/pages/inicio.vue
git commit -am "$_VERSION"
git flow release finish

